### ISSUE TITLE
Layout tweaks in Instructor Home Page

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#2098]
The picture below shows the additional space in the pages that need to be removed for better presentation

![image](https://cloud.githubusercontent.com/assets/5160137/3115453/d75162c2-e708-11e3-81d7-fec0c4791b1a.png)

**Comment by ARSPRodrigo** [comment]
@thyageshm 
you mean like this?
![2098](https://cloud.githubusercontent.com/assets/9689446/6606835/9156b8aa-c860-11e4-8930-aa02931f899a.jpg)
can you assign me to this. :)

**Comment by LowWeiLin** [comment]
@ARSPRodrigo Since you have figured out what is to be done, you can take this issue. You can look for further issues and create pull-requests for them and they will be taken into account, but we may not be able to review them(or assign to you)  during this period. You can look for tougher issues do fix as well.

**Comment by ARSPRodrigo** [comment]
OK Low

**Comment by thyageshm** [comment]
remember to fix all the tests!

**Comment by ARSPRodrigo** [comment]
Sure.

**Comment by thyageshm** [comment]
@ashrayjain since you have been updating the UI of pages, could you fix this one, or close it if this is outdated?

**Comment by ashrayjain** [comment]
@thyageshm yes, this is outdated. The problem near "Sort By" still exists but it will be fixed as part of my issue. Closing this issue.
