### ISSUE TITLE
Change cursor to pointer for the [Edit] link in the comments for the create feedback form

### ISSUE THREAD

**Issue by thyageshm** [TEAMMATES/repo#2301]
Found in instructorFeedbacksPage and instructorFeedbackEditPage

**Comment by ZiXian92** [comment]
I can give this issue a try. Will not be very fast thoug because I am still unfamiliar with the files in the project.

**Comment by damithc** [comment]
Sure. @LowWeiLin can you mentor @ZiXian92  this issue?

**Comment by LowWeiLin** [comment]
Sure. To make the issue clearer, it is referring to the [Edit] link when adding and editing a feedback session. Right now hovering over it shows a text cursor instead of a pointer/hand cursor.

Example:
![image](https://cloud.githubusercontent.com/assets/3910365/5642571/b07d8936-9686-11e4-88a1-42830a41f47b.png)

**Comment by ZiXian92** [comment]
Thanks for the screenshot. Makes it easier to understand.

**Comment by ZiXian92** [comment]
Went to the page on my dev server and realised that the issue can be solved by adding href="#" attribute to the <a> element. However, I am unable to find the HTML files to start editing from as the pages are probably generated dynamically by putting together HTML codes from various files. Also, can I confirm what clicking on the [Edit] link does? Currently nothing happens when I click on it.

**Comment by LowWeiLin** [comment]
Clicking on the link should show more options in the form(in the red box), which should be hidden by default. Is that not happening? The javascript code binding the function do this is in instructorFeedback.js, which i suppose isn't a very good place...

The pages are generated using jsp files, for this issue, instructorFeedbacks.jsp and instructorFeedbackEdit.jsp will be involved. Navigating the code base can be hard but necessary! You can try to using text editors which allow you to search for text throughout the whole project. (e.g. sublime text)

![image](https://cloud.githubusercontent.com/assets/3910365/5695493/4207a266-99e2-11e4-9c2d-880405513eea.png)

**Comment by ZiXian92** [comment]
Yup, what you described is happening. Fixed the 2 files with href="#", which I would like to double check if it is ok to use '#' for href since it does not link to anywhere else.

**Comment by LowWeiLin** [comment]
Does the href="#" change any behaviour? (e.g. page jumps around)
I would prefer if there were a css solution where a class can be added though. It would be clearer what it means/does compared to seeing the href="#" in the jsp.

**Comment by ZiXian92** [comment]
It will go to the top of the page after making the extra options. From my experience with my own devguide website, i used href="" onclick="somejavascriptmethod(value, event);" and then in the javascript function I used ev.preventDefault() to prevent page jump. This eliminates the "#" in the url shown at the bottom of the browser when the mouse hovers over the link. However, this may require some changes in certain javascript functions' signature, which should probably fall under another issue?

**Comment by LowWeiLin** [comment]
That doesn't seem nice...  try to see if you can find a css solution to this instead?

**Comment by damithc** [comment]
You can do a project-wide text search in Eclipse too. Click on the console
panel (not the text editor window) and press Ctrl+H if if remember
correctly.

**Comment by ZiXian92** [comment]
Hmm, guess this works too: a:hover{cursor: pointer;}, which I will put in teammatesCommon.css.
