### ISSUE TITLE
Rephrase 'expand questions' tooltip for big datasets

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2320]
The tip can be like this:

This button is disabled because this session contains more data than we can retrieve at one go. You can still expand one question at a time by clicking on the panels below.

**Comment by shiluka** [comment]
@damithc  

Sir, this tip is also common to 'expand sections' , can I change tip to : 

"This button is disabled because this session contains more data than we can retrieve at one go. You can still expand one at a time by clicking on the panels below."

without specifying 'question' (changed " ... expand one question ..." -> "... expand one ..." in tip) ?

**Comment by damithc** [comment]
Sure. You can also say ' ... one panel at a time ...' ?

**Comment by shiluka** [comment]
got it, thanks sir.
