### ISSUE TITLE
tooltip and placeholder for search bar in InstructorStudentList need to be changed

### ISSUE THREAD

**Issue by franklingu** [TEAMMATES/repo#2353]
Currently the tooltip says "student's name" although the search bar searches all the values in the table. The placeholder can also be changed to reflect this better.

**Comment by chanjunweimy** [comment]
Hello everyone, :) 

I realize this bug is because the jsp is refering to a const in teammates.common.util.Const, and the const value is : "Search for student's name". However, changing the value might cause other's part of the code which referring to this value to change as well. I am not sure whether it is a good way.. Or should I just remove the constant and create a string at the jsp file first? 

Cheers,
Jun Wei

**Comment by Doomdev** [comment]
Can I try this issue ?

**Comment by franklingu** [comment]
just go ahead and submit a pull request later. will be reviewed before merging anyway

**Comment by Doomdev** [comment]
Made 2 changes/Fix  for the Tool Tip Message :)

https://github.com/Doomdev/repo/pull/1
https://github.com/Doomdev/repo/pull/2

Is this correct Fix required :+1:  ? Please Guide me If not ...

**Comment by Doomdev** [comment]
https://github.com/TEAMMATES/repo/pull/3215/files Created only one pull Request ,,

**Comment by Doomdev** [comment]
Is this Fine Sir ?  :) Pull request >>> https://github.com/TEAMMATES/repo/pull/3226
