### ISSUE TITLE
Team members cannot view responses to them if their team name contains html characters

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#2616]
If a team name contains html characters, then in studentFeedbackResultsPage, the responses directed at that team will not appear.

**Comment by bamboo3250** [comment]
Could you tell me how to generate this bug? Because it still appears when I add <div> to the team name like this:

![screenshot_4](https://cloud.githubusercontent.com/assets/8078323/6747521/ea7ca930-cf1d-11e4-8dcb-d1420c7649b1.png)

**Comment by kanghj** [comment]
You need to use another response giver to give the response to the team. You are able to see the response in the screenshot you posted because the student was the author of the response, but you will not be able to view responses written to the team by other students

Notice in this screenshot of the instructor's view, there are 2 responses written to Team 1.
![instructorviewofresults](https://cloud.githubusercontent.com/assets/2216119/6755121/eb40147c-cf5b-11e4-8a17-f3716713978a.PNG)

However, a member of Team 1 is only able to view the response that he/she wrote.
![studentviewofresults](https://cloud.githubusercontent.com/assets/2216119/6755125/f1a687c4-cf5b-11e4-9460-6509d0002b33.PNG)

**Comment by bamboo3250** [comment]
I got the problem. The reason is that characters "<" and ">" are sanitized into "&lt;" and "&gt;" in the file FeedbackResponsesDb.java.

for example, the name of the team is "Team 1 <div>" then it will be "Team 1 &lt;div&gt;"
![screenshot_6](https://cloud.githubusercontent.com/assets/8078323/6762607/17a2f3ae-cfa7-11e4-8bd8-4e5a89d2e8d2.png)

When I assigned the variable "receiver" back to "Team 1 <div>", it worked properly again.

![screenshot_5](https://cloud.githubusercontent.com/assets/8078323/6762622/5c061a26-cfa7-11e4-816b-721ef0acc609.png)

So that means, in the database, the name of the team is stored as "Team 1 <div>" instead of "Team 1 &lt;div&gt;". This may also happen to the other below characters as well, not just "<" and ">".
![screenshot_7](https://cloud.githubusercontent.com/assets/8078323/6763092/a0b6a0e6-cfb1-11e4-88ed-168c696f594b.png)
(In teammates.common.util.Satinizer.java)

The reason this issue only happens to the Team Name but not to students or instructors is that when retrieving data for students or instructors as "receiver", we use their emails, which do not contain special characters, instead of their names. To solve this issue, we can either prevent instructors from entering special characters for the team name OR reverse the sanitization of some characters that do not cause injection like "<" and ">".

I think the later solution is better and simpler.

Please tell me your opinion about this issue. Which solution do you prefer?

**Comment by kanghj** [comment]
I think that currently, reversing the sanitization of html characters in the logic when deciding which responses is visible is better. Perhaps you can try a solution first and make a pull request for this?

Ideally, the escaped characters should not have been stored in the database, so we will actually need another solution for this.

**Comment by bamboo3250** [comment]
@kanghj Okay, I will take this issue. Please assign it to me. I'll look for more other characters whether they will cause the same issue or not.
