### ISSUE TITLE
instructorSessions: omit archived courses from drop-down list

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2771]
Should be done after #1787

**Comment by LowWeiLin** [comment]
To omit sessions from archived courses as well.

**Comment by LowWeiLin** [comment]
One problem with removing archived courses from the list is that the user will not be able to create sessions. (No course to choose from) This problem happens when there are no courses or no active courses.

Another problem is when there are no active sessions: (related to #2847)
![image](https://cloud.githubusercontent.com/assets/3910365/5642658/5cb70d2a-9688-11e4-9d80-af6f44449e42.png)
