### ISSUE TITLE
Private feedback session response rate is wrong

### ISSUE THREAD

**Issue by LowWeiLin** [TEAMMATES/repo#2846]
For private sessions, response rate is shown as "1/1" even when there are no responses.

Applies to InstrutorHomePage, InstructorFeedbacksPage.

**Comment by karan173** [comment]
@LowWeiLin I investigated this issue and found out that - 
1) If a private feedback session has a question for instructor with valid recipients and instructor hasn't responded then response rate is infact 0/1.(like public sessions).
2) However if the the private feedback session has a question for instructor with no valid recipients and instructor hasn't responded(actually he can't respond since there are no valid recipients), then response rate is 1/1(unlike public session where it will be 0/1).

So, I don't know which approach is correct. Should I make the private sessions behave like public in this context?

**Comment by LowWeiLin** [comment]
#3203 is basically the same issue. (Will close that one)

By right, the response rate should show either "0/0", "0/1" or "1/1" depending on whether the instructor has any questions to answer, and if he answered any.

If the code to do this is too costly however, we can consider showing something like "N/A", since this is not very important/informative.

**Comment by damithc** [comment]
I like the 'N/A' idea.

**Comment by karan173** [comment]
What should be the response rate in the case, the instructor has a question to answer, but the question has no valid recipients(in which case, the question is not showed to him)?

**Comment by LowWeiLin** [comment]
if the question is not showed to him, then there can't be any responses. So we would expect 0 responses and it should be 0/0.

**Comment by karan173** [comment]
For a public session, the response rate in this case is 0/1. (Eg, create a public session in a course with no students. Add a question for an instructor with students as recipients).

**Comment by LowWeiLin** [comment]
Ah okay... I think the correct way is not being done as it is costly to calculate the number(many db reads needed). The wrong cases are usually rare(such as no students). It would be good if it can be fixed, but otherwise, I think an estimate is still fine.
