### ISSUE TITLE
instructorFeedbackSessions: mention that archived sessions are not shown

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2861]
Users might get worried if they don't see those sessions.
It can be a simple message under the sessions table.

**Comment by drunken-saint** [comment]
I think i can do this . Please assign the issue to me. I am thinking to create a seperate division (<div>)
with a <p> element in it depicting the message . 
Is there a bg color to be assigned to ?

**Comment by kanghj** [comment]
It can just be a simple message below the table showing the sessions, so maybe make it without a background colour.

**Comment by kanghj** [comment]
The sessions page is a jsp file. It's src/main/webapp/jsp/instructorFeedbacks.jsp.

**Comment by drunken-saint** [comment]
made the changes . Here is  a screenshot.Now creating a pull request for further discussion. 
![screenshot 51](https://cloud.githubusercontent.com/assets/7551036/6045591/6ff9920a-acc1-11e4-82e8-ef8eaa5201f8.png)

**Comment by drunken-saint** [comment]
Should I add a "Note :" before the message also . I didn't do it as there are no other messages with such format . It'd have looked a bit odd .

**Comment by kanghj** [comment]
There are two tests which are failing on master now, so if you have merged master in, then the two tests will fail. For this issue, you can ignore the mismatches unless the expected html contains the sessions page, then it is related to this issue and you should change the expected html to include the message you've added.

Check that you are modifying the html file under src/test/resources/pages, and not in another directory. You can post some screenshots of the mismatches, so we can have a better look at it.

**Comment by drunken-saint** [comment]
my repo is failing total 4 tests after all the changes I've made . including the change in instructorFeedbackEmptyAll.html . Out of the 4 , 2 are to be ignored as you suggested .And , one of the issues is InstructorsFeedbackResultsPageUiTest  which too can be ignored right now . So , Only  a single failed test is of concern now :  InstructorFeedbackResultsPageUiTest. I am attaching the screenshot of the stack trace .


![screenshot 55](https://cloud.githubusercontent.com/assets/7551036/6215512/53b2645e-b627-11e4-9d3f-5ba094be63fb.png)
Here are the expected-actual screenshots
![screenshot 56](https://cloud.githubusercontent.com/assets/7551036/6215526/6e710534-b627-11e4-83b3-48d843e548e5.png)
![screenshot 57](https://cloud.githubusercontent.com/assets/7551036/6215548/88270276-b627-11e4-9f98-ef23bf3b4225.png)
I don't know why the second one is occuring . I've made those changes in the instructorFeedbackEmptyAll.html . And , yes I've checked for the src destination too.

**Comment by kanghj** [comment]
If you are certain that you edited the correct file, then the mismatches are occurring in a different file. My initial comments might have been a bit misleading and unclear. Usually in every test, there are several html comparisons that will be done, so changing just <code>instructorFeedbackEmptyAll.html</code> is not sufficient for the test to pass. You can check the test failures to see which files are causing the failure. 

![findtesthtml](https://cloud.githubusercontent.com/assets/2216119/6222359/0962408e-b68d-11e4-8a39-9d68b4fd647a.PNG)


For example, if you go to the bottom of the Failure exception panel, you can see the stacktrace, and the line that the test failed on (the above example shows line 148 in AdminHomePageUiTest failing, although this is not relevant to your issue). 

When you go to the line that is causing the failure, you can then check the file name of the test html file that is causing the failure, you should then make the changes to this file. 

Alternatively, since your changes will affect most, if not all, of the html comparisons in InstructorFeedbackPageUiTest, you can just find all the html files that are checked against and edit them. As an example, <code>feedbackPage.verifyHtmlMainContent("/instructorFeedbackEmptySession.html");</code>, on line 111, shows that instructorFeedbackEmptySession.html is tested against. Look for the filenames passed into the functions <code>verifyHtmlMainContent</code>, <code>verifyHtml</code>, <code>verifyHtmlAjax</code>.

In addition, there are several html files in AdminHomePageUiTest that test the sessions page, although the test is currently failing on an earlier unrelated line. You will have to make changes to the following files : <code>newlyJoinedInstructorFeedbacksPage.html</code>,<code> NJIfeedbackSessionRemind.html</code>, <code>NJIfeedbackSessionPublished.html</code>, <code>NJIfeedbackSessionUnpublished.html</code>.

**Comment by drunken-saint** [comment]
Hi there, 
I merged my repo with the Teammates repo . and Now I am getting 800+ compile errors all in the java directory. Their description suugests some problem with the Google App Engine SDK . should I update my SDK to the latest version or is it some other alternative available?
Or , Should I fork and clone again from the TEAMMATES/repo?  
And , I know this issue has taken way longer than it required . At first, I was busy dealing with my mid-semester exams and fell ill afterwards .Meanwhile, I also read about software testing and hopefully, will be able to get things such as writing and modifying the tests ,soon by myself.  Anyways , I am back. And will try to resolve this issue ASAP .
Thanks.

**Comment by kanghj** [comment]
Hi, it is nice to see that you are back. 

The Google App Engine SDK version on Teammates did not change, so you shouldn't update your SDK to the latest version. Perhaps you changed the project settings accidentally? In eclipse, check Project → Properties → Google → App Engine to see if the right version of the SDK is used. Also, look though the rest of the troubleshooting guide.

**Comment by drunken-saint** [comment]
Hi , I've installed a fresh copy of the recommended SDK version suggested at the settingUp.md file only. There are no compile errors now . Lets get the issue resolved now.

**Comment by drunken-saint** [comment]
Hey, I've made the rquired changes all also changed the required files for the test cases . 
Now , only 3 tests are failing :
1. InstructorsFeedbackResultsPageUiTest (which fails on some systems)
2.AdminHomePageUITest(failing on master , not related to this issue)
3.InstructorFeedbackEditPageUITest(failing on master , not related to this issue)

I think it its good to merge now , I am creating a pull request for further discussion (https://github.com/TEAMMATES/repo/pull/3047).
@kanghj  Thanks for your support . Your advice helped me get a better understanding about the test cases .
