### ISSUE TITLE
'No active courses' in masquerade mode

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2889]
Sessions page in masquerade mode show 'no active courses'

**Comment by damithc** [comment]
May be using the 'logged in user' in some place instead of the 'nominal user'?

**Comment by kanghj** [comment]
This could be caused by the changes @LowWeiLin made in #2872, if the script included in that pull request wasn't ran. This is since the query would now filter on the isArchived attribute. The isArchived attribute wasn't indexed prior to the pull request and the query would return no results, which seems consistent with this issue.

**Comment by damithc** [comment]
Yes, that seems to be the case.
