### ISSUE TITLE
Cannot see full respondent name in submitted responses

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#2990]
See screenshot. The part of the name shown may not be enough. 
![image](https://cloud.githubusercontent.com/assets/1673303/6198119/92d717a6-b42e-11e4-9423-bdd836db44a6.png)

**Comment by arvind-kalyan** [comment]
Sir, Can I try this one?

**Comment by arvind-kalyan** [comment]
Three approaches : 
1. Reduce font size
2. Increase the length of the drop-down box.
3. Combination of both 1 and 2.
How much characters should we show on the screen? (that is, length of the box).

**Comment by damithc** [comment]
Let's see if we can increase the number of visible letters to 15. Try a few combinations and post screenshots. When posting screen shots, I would like to see the full width of the page, not just the corner. That is, not as done in the screenshot above.

**Comment by arvind-kalyan** [comment]
Ok sir.

**Comment by arvind-kalyan** [comment]
Sir, just to be sure, this is the page when Instructor is giving feedback to one or more students (as an essay question), in instructorFeedbackSubmissionEditPage correct?

**Comment by damithc** [comment]
@LowWeiLin it is applicable to studentFeedbackSubmissionEditPage as well right?

**Comment by arvind-kalyan** [comment]
Sir I have modified the bootstrap grid split from 2-10 to 4-8, giving more space to the drop-down box. The max-width is set to 170px instead of 125px, increasing the length to 15 chars. I have attached the screen-shots.
![2990_2](https://cloud.githubusercontent.com/assets/5078299/6429568/3ad986c2-c001-11e4-9ff4-c0c06370c62c.png)
![2990_1](https://cloud.githubusercontent.com/assets/5078299/6429569/3dd0de8e-c001-11e4-819b-aedff898f747.png)

There is a lot of space remaining to left of the dropdown boxes, it's because the default was align:right. Should I change those as well?

**Comment by arvind-kalyan** [comment]
Another possibility : 
I have made align:**center**.

![2990_3](https://cloud.githubusercontent.com/assets/5078299/6429700/bc002770-c00a-11e4-837c-1d7a07ca820e.png)
![2990_4](https://cloud.githubusercontent.com/assets/5078299/6429703/ed400832-c00a-11e4-847f-7b8d4dcdde0f.png)

**Comment by damithc** [comment]
I think the previous alignment is fine. Centre alignment moves the name and
response farther apart, which is not good.
4-8 split seems to be fine. Can we show more letters in that split? There
seems to be lot of empty space on the right and the left of the name.

**Comment by arvind-kalyan** [comment]
Sir, 
Yes, it can be done by adding a "width" property. Here I have set width (and max-width) to be **275px**

![2990_5](https://cloud.githubusercontent.com/assets/5078299/6430910/e096fcc8-c044-11e4-9a4d-56460df1e1cb.png)

![2990_6](https://cloud.githubusercontent.com/assets/5078299/6430912/e39adfac-c044-11e4-9cff-d00e8f57c646.png)

How is it?

**Comment by damithc** [comment]
@LowWeiLin do you foresee any problems? If not, @arvind-kalyan can proceed.

**Comment by LowWeiLin** [comment]
@arvind-kalyan You can try adjusting the width of the browser window, and see if it generally looks fine even when the width of the browser is small. No need(but good if possible) to cater to very small screen widths like for phones since the rest of the site does not really scale well either.
Other than that, it should be fine.

**Comment by arvind-kalyan** [comment]
@LowWeiLin When width of the browser is small, "**To:**" comes on right end of a line and drop-down comes on the next line at left end. But this happens even in the initial setting (without any changes). Other than this, there is no other problem to be seen.

**Comment by arvind-kalyan** [comment]
What should I do? Shall I proceed?

**Comment by LowWeiLin** [comment]
Yes, it seems fine. Do proceed.
