### ISSUE TITLE
Instructor count includes testing accounts in adminAccountManagementPage

### ISSUE THREAD

**Issue by karan173** [TEAMMATES/repo#3050]
Instructor count should not include testing accounts. Also see [link](https://groups.google.com/forum/#!topic/teammates-contributors/kVHhpDI-fAs)

**Comment by damithc** [comment]
@karan173 you mentioned two different issues. Can you submit them as two separate issues? They are easier to track that way.

**Comment by karan173** [comment]
@damithc Done. Can you please verify the issues and assign them to me.

**Comment by damithc** [comment]
@ymoctavia can you verify this bug?

**Comment by ymoctavia** [comment]
Yes, the "count in gray" does not exclude testing accounts. for example:
![image](https://cloud.githubusercontent.com/assets/7552558/6539955/f557d5c6-c4c0-11e4-864d-834983c47856.png)

We can actually remove this count because we now have a count in the panel. like below:

![image](https://cloud.githubusercontent.com/assets/7552558/6539968/62b98920-c4c1-11e4-9641-c5caf334a499.png)

This counting in the panel heading will be updated using javascript automatically with the actual numbers of rows being shown in the page. We use "all=true" to show all accounts including testing accounts and "all=false" or simply ignore it to exclude the testing accounts.

**Comment by damithc** [comment]
Thanks for the clarification @ymoctavia and for posting the issue @karan173

**Comment by karan173** [comment]
Can I be assigned this issue? We have to remove the "count in gray" right?

**Comment by LowWeiLin** [comment]
@damithc Do we remove the "count in gray" to solve the issue or correct the value?

**Comment by damithc** [comment]
Let's remove it.
