### ISSUE TITLE
[Testing] After the Completion of Testcases browsers should be closed Automatically

### ISSUE THREAD

**Issue by suhas355** [TEAMMATES/repo#3108]
As Observed, In some testcases after completion successfully/unsuccessfully browser should be closed in order to reduce system load.

Using annotations for failure and success, data should be reverted back to stable state (if possible) and  
driver.close() should be done

**Comment by atishay100495** [comment]
I've added the close browser functionality for the ui browser tests in my branch Issue3108. I've created a pull request for the same. Please review and push the changes if they look good.

**Comment by LowWeiLin** [comment]
As mentioned in #3122 

"Starting a browser takes a long time. That's one reason why we reuse the browser. Furthermore, we may want to see the browser content in case the test case failed. That's why we don't want to close the browser after the test. One can edit the BrowserPool.java if one wants to use a fewer number of Browsers."
