### ISSUE TITLE
Main Titles(h1 tags) are covered by navigation bar for a certain page width

### ISSUE THREAD

**Issue by BillyZafack** [TEAMMATES/repo#3293]
The titles(h1 header) of all the pages on the instructor's page(Home, Courses, Sessions, Students, comments, search and help) are covered up by the navigation bar when the pages width is less than 992px(responsiveness fault).

**Comment by acruis** [comment]
768px is when the navbar will turn into a hamburger menu, so the question is what to do between the 768px and 992px area.

There are multiple ways we can approach this when window size is between 768px and 992px:

* **Ugly 1:** Decrease font size
![font size decrease](https://cloud.githubusercontent.com/assets/8437638/7082206/a2f3952c-df82-11e4-9b2d-459f83355927.png)
* **Ugly 2:** Just add more padding to the body
![add more body padding](https://cloud.githubusercontent.com/assets/8437638/7082270/d8d9b7c4-df83-11e4-9ddf-2f73392d9849.png)
* **Decent 1:** Morph into hamburger menu immediately when window size is below 992px
![without class change](https://cloud.githubusercontent.com/assets/8437638/7082278/fad914b4-df83-11e4-8a21-daa1eaaad8cf.png)
* **Decent 2:** Morph into hamburger menu, and change the behaviour of container to mimic container-fluid (auto width instead of fixed width) (which is being done by Bootstrap at <768px screen sizes anyway)
* **Doesn't work:** Change behaviour of container to mimic container-fluid but don't morph into hamburger menu
![image](https://cloud.githubusercontent.com/assets/8437638/7082344/31b1153a-df85-11e4-9077-fe710ae0016b.png)
Only works for widths between 907px and 992px. Between 768px and 907px, same problem applies:
![image](https://cloud.githubusercontent.com/assets/8437638/7082348/561dca76-df85-11e4-819e-c0be199131f6.png)

I am implementing Decent 2 for now, but if another design is preferred, please do tell me too.

**Comment by damithc** [comment]
Go ahead :-)
