### ISSUE TITLE
'Expand questions' button is not visible on InstructorFeedbackResultsPage if results are loaded by ajax

### ISSUE THREAD

**Issue by kanghj** [TEAMMATES/repo#3300]
Currently on master, the button is not shown if the data is incomplete:

![noexpandbutton](https://cloud.githubusercontent.com/assets/2216119/7072067/1cd9a9e2-df1c-11e4-94eb-8d7d15e2aafe.PNG)

The correct behaviour,:
![withexpandbutton](https://cloud.githubusercontent.com/assets/2216119/7072622/6929f19a-df20-11e4-8f68-684d737d3024.PNG)

In instructorFeedbackResults.js, line 299 hides the button.
<code>

        if($(".panel-success").length > 1 || $(".panel-info").length > 1){
              $('#collapse-panels-button').show();
        } else {
              $('#collapse-panels-button').hide();
        }
</code>

This error seems to be because in #3026, the css class for the panels changed, so the above javascript will hide the button. 
.

**Comment by wkurniawan07** [comment]
As the one working for that issue, I should be responsible for this.
One thing to confirm though: do any of the questions shown in the "Expand Question"-less page have responses? Because if not, no point in allowing user to expand/collapse anyway.
I foresee a straightforward fix, if needed. Hope I'm not wrong.

**Comment by kanghj** [comment]
Yes, they have responses.

**Comment by wkurniawan07** [comment]
does this "error" come from `InstructorFeedbackResultsPageUiTest`, specifically line 240?

**Comment by kanghj** [comment]
Yup

**Comment by wkurniawan07** [comment]
Ah, this is one thing that was puzzling me back then (and now that the issue is raised again) when I re-wrote the test pages. Because `instructorFeedbackResultsAjaxByQuestion.html` (the guilty test file) actually expected all (yes, all) the questions in to have no responses (then it comes back to my previous argument), but it turned out that some responses appear and yet the comparison is still successful. Is it due to the ajax?

**Comment by kanghj** [comment]
When loaded by ajax, the responses are loaded only when the user clicks on the panels to expand them. So when the page actually loads and the comparison is done, there are no responses and the comparison is successful?

**Comment by kanghj** [comment]
Actually, I think this error only affects testing and not if the session has many responses. But it will be good to make the button appear in the test's html.
