### ISSUE TITLE
student feedback submission: Some students are not sure if the responses were saved because the same page loads afer submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3323]
Although the status message clearly says 'All responses submitted succesfully!' a few students didn't noticed that and emailed me asking if the responses were saved. One problem may be that the status message appears halfway down the page.
![image](https://cloud.githubusercontent.com/assets/1673303/7158854/7dffef40-e3b0-11e4-8c80-b3e7af4c5731.png)

**Comment by MrFool** [comment]
Ok, this only happens when the student is accessing and doing the submission while not being logged in -> I did a really simple fix which is to shift it upwards at #3325 

![screen shot 2015-04-17 at 10 25 56 pm](https://cloud.githubusercontent.com/assets/6291947/7203959/2d6a6536-e551-11e4-8659-4fd896683d77.png)

As we can see, now the status message will be right below "submit feedback" and students will less likely miss it.
