### ISSUE TITLE
submission UI for contribution question: values not colorized

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3344]
See screenshot. Selected values are not colorized. Noticed this in 'moderate' page, but may be applicable to other places as well.
![image](https://cloud.githubusercontent.com/assets/1673303/7271703/bec283fa-e917-11e4-9955-184cfee60ab4.png)

**Comment by MrFool** [comment]
What is the expected behavior? Getting this on local dev latest master in a moderation page.

![screen shot 2015-04-23 at 10 45 36 pm](https://cloud.githubusercontent.com/assets/6291947/7299778/89e502ae-ea0a-11e4-8fe6-a1bf40edd3f6.png)

Initial value was not colorised, but after I change them it was, so "Jun De" response is initial and the rest were changed

**Comment by damithc** [comment]
Say you save these values and come back to moderate the values again
sometime later. The values will not be colorized when you load the page for
the first time (they should be). I guess the 'colorize' function is
activated upon edit/change event only.

**Comment by MrFool** [comment]
Ok, so there is no need to differentiate between non edited values and edited values, all values including "Not sure" should be colorized?

**Comment by damithc** [comment]
Yes.

**Comment by MrFool** [comment]
Hmm ok, so I did a little digging, moderate uses the same JavaScript files as student feedback submission edit page, this means that if we make the above changes:

Students will also now see all contrib (and other related colorized questions) initially loaded with options all colorized as green.

Was the intention of colorizing it meant to indicate for students that a 'non-default' option has been selected whereas for instructors that 'you are currently editing a response that has been made by the student' and therefore permanently colorized green?

**Comment by MrFool** [comment]
Update: 

Ok, I get what is happening now after more digging, I managed to get it to work for contrib questions but this will take awhile, I'll update it over the next couple days incrementally and when it's ready I'll do a PR.

**Comment by MrFool** [comment]
Before intended changes:

![screen shot 2015-04-24 at 5 59 13 pm](https://cloud.githubusercontent.com/assets/6291947/7316690/b891acbe-eaab-11e4-8c9e-4171096bdd49.png)

After intended changes:

![screen shot 2015-04-24 at 5 59 37 pm](https://cloud.githubusercontent.com/assets/6291947/7316697/c5499188-eaab-11e4-9392-0a6b6de7509d.png)

Ok, so after sufficient digging you're right, it is applicable to other places including student edit page and any other pages that uses the same JavaScript files because they use the same feedbackSubmissionEdit.js file and the colors are never updated until a 'on-change' event is fired.

**Comment by damithc** [comment]
The original intention is to minimize user mistakes (e.g. choosing +10 when
meant to choose -10) by adding matching colors to values. It is fine if the
values have the matching colors all the time.

**Comment by MrFool** [comment]
I apologise:

I misunderstood the intention earlier and did not take enough care into seeing that the initial color was 'black' as in default for 'equal share' whereas it should be 'gray' and 'neutral' (also: red for negative, green for positive even on initial loading), I understand better now and will incrementally work on this issue over the next week, exams are around the corner so it might take longer than usual :)

**Comment by damithc** [comment]
Can do after exams. No hurry.
