### ISSUE TITLE
instructor view results: contribution question, giver column sorting is broken

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3346]
See screenshot. This is the 'by question' view. May be broken in other places too. Also need to add missing tests to catch it.

![image](https://cloud.githubusercontent.com/assets/1673303/7271825/bf602c8a-e918-11e4-9749-61f854a21ac3.png)

**Comment by wkurniawan07** [comment]
This is caused by line 183 in common.js, part of the sortTable algorithm:
`var innerText = RowList[i].cells[colIdx-1].innerHTML;`
`.innerHTML` will capture EVERYTHING inside the table content, including div wrappers etc. For pure texts, `.innerText` should be used instead.
I believe this is an uncaught regression introduced by #3028. @JosephineKwa hi again :p (don't blame yourself, I'd totally overlook this too had I worked on that issue)
I'll leave this to someone else to work on.
