### ISSUE TITLE
AdminHomePageUiTest test fails sometimes on line 270

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3459]
Invocation error

**Comment by MrFool** [comment]
InvocationTargetException - happened a 2nd time within 5 test suite runs

**Comment by kanghj** [comment]
Seems to be a problem with the bad responses getting generated:

![wrongquestiontype](https://cloud.githubusercontent.com/assets/2216119/7763575/981add68-0075-11e5-9b99-8b65949b78ca.PNG)

Somehow, the contribution question is getting responses when the question type is TEXT when the admin adds the instructor. Could be a problem with the live server as well, since the response generation is handled by our logic, and not the backdoor.

**Comment by MrFool** [comment]
Doesn't seem to happen in new test file from #3491, will open if it happens again
