### ISSUE TITLE
StudentCourseJoinConfirmationPageUiTest is failing on live server

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3499]
Failing on line 94 `confirmationPage.verifyHtml("/studentCourseJoinConfirmationHTML.html");`

**Comment by wkurniawan07** [comment]
is this because of the new testng config file?

**Comment by kanghj** [comment]
It's likely failing because of the logout link at the bottom:
<code> <a id="button_cancel" class="btn btn-danger" href="/_ah/logout?continue=%2Fpage%2FstudentCourseJoinAuthenticated%3Fkey%3D{*}%26next%3D%2Fpage%2FstudentHomePage">No, this is not my account</a> </code> should have checked for a wildcard
