### ISSUE TITLE
student feedback submission: user is confused because the same page reloads after submission

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3569]
Some users are not sure if the submission was saved correctly because TEAMMATES loads the same page after the user pressed the 'submit' button.

**Comment by kanghj** [comment]
Similar to #3323. The fix for that (moving the status message) hasn't been deployed to the live server yet, I think. Maybe the fix for that will help. If students are still confused after that, maybe we should remove the message for "You are submitting feedback as ...", or change the contents of the message, after the student have submitted their responses.

**Comment by MrFool** [comment]
Yes, we haven't pushed a new version in awhile so many of the fixes that were in just recently never got the chance to see live yet.

**Comment by damithc** [comment]
In that case we'll deploy that fix first and see how it goes.

**Comment by damithc** [comment]
More user complaints about this issue. Some students don't notice the status message. May have to do more. actually, success messages should be green. 
We can also send an email acknowledgement. 
To be done later after the jstl conversion is over.

**Comment by taniach** [comment]
@kanghj How can I replicate this bug?

**Comment by taniach** [comment]
This page now shows a green status message 'All responses submitted succesfully!' Should we still navigate to a different page after the student clicks 'Submit'?
