### ISSUE TITLE
Correct page type not being tested consistently

### ISSUE THREAD

**Issue by MrFool** [TEAMMATES/repo#3687]
![screen shot 2015-06-11 at 4 05 19 pm](https://cloud.githubusercontent.com/assets/6291947/8102573/afe09cc4-1053-11e5-9e8f-e78d7ea798f4.png)
![screen shot 2015-06-11 at 4 04 00 pm](https://cloud.githubusercontent.com/assets/6291947/8102575/afe23bba-1053-11e5-86a0-e3b08dfe32ab.png)
![screen shot 2015-06-11 at 4 03 49 pm](https://cloud.githubusercontent.com/assets/6291947/8102576/afe2d2aa-1053-11e5-9fe3-e4dffe96f96a.png)
![screen shot 2015-06-11 at 4 03 44 pm](https://cloud.githubusercontent.com/assets/6291947/8102574/afe0b51a-1053-11e5-8c2b-c6e7987f7f0d.png)

We should make it consistent and not test for HTML tags, increases fragility and the HTML tags are already tested once we verify HTML at least once, not much point to test it here when we're looking only for whether it has the correct page header.

**Comment by damithc** [comment]
The idea is to check if we are in the correct page, not if the page content is correct. This is used to detect when the browser ends up in a different page than intended (e.g. goes to login page instead of the intended home page). So, it is fine as long as the check is against a small piece of content that is unique to that page and unlikely to change soon. Other than that, yes it is good to standardize and make the test less fragile.

**Comment by MrFool** [comment]
Yupp, understood, the content inside the headers are unlikely to change, but the HTML tags might change (some were using h2, h3) but because of migration to JSTL, they're all going to be h1 (except rare cases) once we template it and make it consistent.

Indeed, it is a strong enough check just by checking the page title, adding the header1 tag checks makes it more fragile than it needs to be

**Comment by MrFool** [comment]
In JSTL-Dev, closing
