### ISSUE TITLE
instructor feedback edit: previous values are lost when reporting incorrect end time

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#3693]
For example, if the end time is earlier than start time, the page is reloaded with the error message, but reverts back to earlier values instead of loading with the values the user was trying to save.

**Comment by kanghj** [comment]
This is happening because the form submission redirects to the original page, which loads the feedback session from the database. It could get messy trying to pass all the values that the user modified as parameters to the page. 

I can either remove the redirection and just make the action show the page, or change the code to submit the form using ajax, which would likely be a better solution here.

**Comment by damithc** [comment]
I like the ajax solution, but no need to do urgently. In general, I would like to use ajax more, but we need to think it through first.
