### ISSUE TITLE
Use $(document).on('ready'... instead of onload

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#3769]
document ready event fires earlier than onload and if we are attached frontend value checks or certain important JavaScript stuff, attaching it to onload may cause some problems on slower connections.

**Comment by MrFool** [comment]
currently our onload is also attached to the body, we should seperate it into the JavaScript files instead so we always know where to look for event handlers rather than guessing.

Also, onload only allows for one event listener whereas document ready allows us to "attach" it multiple times, i.e. we can have one HTML file that references different JavaScript and all of them does document ready there will be no problem but if they all use onload they will be sort of 'overriden'.
