### ISSUE TITLE
Improve AJAX request failure handling

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4082]
This arises from the discussion in #4072 
Currently (and going to be scraped soon) it's only console.logging `'Error'` or `'AJAX request failed'`, neither of which is helpful.
Refer to commit cf969fc.

**Comment by junhaoyap** [comment]
In cases like this when an AJAX request fails, we should tell the user something along the lines of "Something has gone wrong, please try again in a few moments blah blah please contact blah blah if the problem persists.." instead of logging and silently failing :)

**Comment by yj-soh** [comment]
With reference to cf969fc.
Would it be better to have this as one PR, multiple PRs, or multiple PRs to be merged into one?

@damithc Do take a look. I'm not quite sure how exactly should these AJAX errors be handled.

---

**instructorCourseEdit.js**

`checkPrivilegesOfRoleForModal()`

**Success:** Shows a modal with the privileges of an instructor role.
**Failure:** Shows a modal with the those of the last role checked (default's Co-owner).

This cannot be triggered normally. Either not show the modal on undefined or just keep the current behaviour. It's read-only, so there's no real problem.

`checkPrivilegesOfRoleForInstructor()`

**Success:** Checks privileges for an instructor role.
**Failure:** Does nothing.

Also cannot be triggered normally. Can probably be unhandled since it should do nothing if the role's undefined.

---

**instructorCourseEditAjax.js**

`editFormRequest()`

**Success:** Appends edit form onto instructor view area.
**Failure:** Loading spinner remains, nothing else happens.

Remove the spinner and add an error message into the Edit button?
There should be no other changes, so the main question is where to put the error message.
I personally believe changing the message in the Edit button is sufficient.

![2015-09-21_18-23-56](https://cloud.githubusercontent.com/assets/8586080/9989764/f131d96a-608d-11e5-8a28-92d6e1c27ea7.png)
![2015-09-21_17-31-17](https://cloud.githubusercontent.com/assets/8586080/9989747/c760b20a-608d-11e5-9cd0-73a7069d4396.png)

---

**instructorFeedbackEdit.js**

`getVisibilityMessage()`

**Success:** Gets messages for the visibility of a question from the server and replaces the current visibility messages. Shows the messages and hide the options.
**Failure:** Hides the option, shows nothing in return. Upon hitting an error, the messages will not be displayed upon retrying unless the options are changed (due to a check to prevent duplicate requests).

Either show an error message where the visibility messages are shown or show the visibility options with an error message on the Preview Visibility button like above?

---

**instructorFeedbacksAjax.js**

**Success:** Appends list of sessions onto page on page load.
**Failure:** Loading spinner remains, nothing else happens.

This should not even happen unless the server goes down with the page loaded halfway.
Show an error message where the list would usually be? The status message div can be used for this.
Should we get the user to refresh the page or to click something to retry?

---

**instructorStudentListAjax.js**

`seeMoreRequest()`

**Success:** Replaces table of student data for a particular course.
**Failure:** Loading spinner remains, nothing else happens. Upon hitting an error, the students are not loaded even after clicking more times.

Show an error message, maybe similar in design to the one in instructorHome?

---

**studentMotd.js**

**Success:** Shows the student motd.
**Failure:** Shows the student motd container without the motd.

This should not even happen unless the server goes down with the page loaded halfway.
Maybe just hide the motd container entirely? It seems odd telling students to retry loading a motd.

---

**instructorFeedbackResultsAjaxByGQR.js
instructorFeedbackResultsAjaxByGRQ.js
instructorFeedbackResultsAjaxByRGQ.js
instructorFeedbackResultsAjaxByRQG.js**

Handled in 9eb6782d0fb7e1f0f4bc0655b297b8b97821596e

**instructorFeedbackResultsAjaxByQuestion.js**

Handled in 0ce48b93c60f6f199c5a344595fde7ec94066b0a

**instructorFeedbackResultsAjaxResponseRate.js**

Handled in 18fd4ee462ac298c021405b061716fb062533ab3

**Comment by damithc** [comment]
@yj-soh can add screenshots to some of the 6 situations? I need to see the UI of each situation to get some context.

**Comment by yj-soh** [comment]
@damithc Updated the previous comment with screenshots for the current success and error cases, as well as some possible solution mockups.

**Comment by damithc** [comment]
1. ok, no need to handle
2. suggestion ok
3. either suggestion is ok
4.suggestion ok
5. suggestion ok
6. ok, can hide container

**Comment by damithc** [comment]
May be do as separate issues?
