### ISSUE TITLE
Student who submitted responses shown as not submitted

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4134]
A student who has submitted all questions except one is shown as 'not responded to any question'

**Comment by damithc** [comment]
If the bug is confirmed, we need a hot patch on top of V5.47 (the current public version)

**Comment by LowWeiLin** [comment]
Does the student's responses show up in the results page?

**Comment by damithc** [comment]
Yes

**Comment by damithc** [comment]
No duplicate student entity either.

**Comment by LowWeiLin** [comment]
We have a Set that records which student/instructor has responded. I suspect the problem lies there but i'm not sure how it happens yet. Looking into it.

**Comment by kanghj** [comment]
This is unlikely, but does the student's email have any special characters? The responding students list makes use of retrieving responses from the database to update itself, due to the sanization issue, it might have failed to retrieve the student's responses and think that the student hasn't responded.

**Comment by damithc** [comment]
Student has missed one row in one rubric question. I doubt if that is the problem though. May be updating the set was not done properly or an update got lost due to distributed database issue?

**Comment by damithc** [comment]
No special characters in the email.

**Comment by damithc** [comment]
I went to the 'moderate' option and saved the student response again. Now his name does not appear in the 'unsubmitted' list. So it looks like the set did not get updated properly at the time he submitted. But just to be sure, try to change the email of a student and see if the set is updated to the new email.

**Comment by kanghj** [comment]
I tried changing a student's email and the set is properly updated.

**Comment by damithc** [comment]
So this could be a case of rare update to the set getting lost. May be we should run a script to go through sessions and identify other similar cases? At this point we don't know how bad this problem is.

**Comment by kanghj** [comment]
Anyway, this issue is likely due to eventual consistency. The submission action updates the respondents set after querying the database for the submitter's responses. If the responses hasn't persisted, then the submission action will incorrectly fail to add the submitter into the respondents set. 

A possible solution would be to that part of the action to add the respondent based on the current submission. However, this will not work for FeedbackQuestionSubmissionEditSaveAction (the submission page with only a single question), because that action will not have the necessary data from the form submission, and will still need to do the database query.

**Comment by damithc** [comment]
A user reported another case. So we need to fix it. Yes, it must be the eventual consistency thing. 
The single question thing is not widely used, so we can go ahead with the proposed remedy. In theory, we should be able to update the set immediately after saving the responses without querying the database further.
