### ISSUE TITLE
Rubric questions: show unmarked rows in a different color

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4135]
In a rubric question, it is easy to miss a row. May be we should show unmarked rows in a different way so that if a row is missed, it is more obvious?

**Comment by LowWeiLin** [comment]
We could set the background of the question cell(or the entire row?) to be green if it is answered, and leave unanswered rows white:
![image](https://cloud.githubusercontent.com/assets/3910365/9457102/e620e43a-4b11-11e5-8cd6-5bb5c6976566.png)

Marking the unanswered rows may seem abit messy at the start as all of the rows will be marked.

Alternatively, we could use a tick icon in the question cell instead of changing the background color.

**Comment by damithc** [comment]
Perhaps color the entire row in green? Or, color the selected cell in green
and the other cells in blue?

**Comment by LowWeiLin** [comment]
Like this? I think having the entire row in green is clearer.
1)
![image](https://cloud.githubusercontent.com/assets/3910365/9457536/4e75687c-4b16-11e5-9c79-92a91953e5c3.png)
2)
![image](https://cloud.githubusercontent.com/assets/3910365/9457574/ad74fc0c-4b16-11e5-894e-2ff8b96b575d.png)

**Comment by damithc** [comment]
Yes, like option 1 but the selected cell should be blue. or the selected cell is green and the remainder of the row is blue.
