### ISSUE TITLE
status message hidden by nav bar

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4154]
The page is supposed to auto-scroll to the status message. Currently, it does that, but the message goes behind the top nav bar. We had a solution for this in the earlier version which seems to have regressed.

**Comment by damithc** [comment]
@taniach , can have a look?

**Comment by damithc** [comment]
I don't think we can do the public release without fixing this one.

**Comment by yj-soh** [comment]
Is there a specific page this happens on?
Also, how long is the page and how did you get to it?

**Comment by kanghj** [comment]
Can be replicated by submitting responses to a feedback session, the statusMessage will be hidden behind the navbar on studentHome. The difference seems to be because <code>document.getElementById('statusMessage').scrollIntoView(); </code> is now ran on document.ready, whereas in the old version, the javascript is executed while the document was still getting parsed. A quick fix now will be to remove the document.ready handler.

**Comment by yj-soh** [comment]
Would it be better to call it with a `false` to align it to the bottom of
the page or scroll it with an offset, though?

**Comment by taniach** [comment]
Ok I am doing it

**Comment by taniach** [comment]
We can scroll with an offset slightly greater than the height of the navbar.
