### ISSUE TITLE
status message for updating sessions should be green

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4191]
Currently, the status message shown after updating a session is yellow. It should be green.

**Comment by taniach** [comment]
This involves changing `instructorFeedbackEdit.js`. The status message colour is already configured as green in `InstructorFeedbackEditSaveAction.java`. However, this is getting overwritten by the function `bindFeedbackSessionEditFormSubmission()` in `instructorFeedbackEdit.js` since the message comes from an AJAX request.

**Comment by damithc** [comment]
What's the proposed solution?

**Comment by taniach** [comment]
Change `alert alert-warning` to `alert alert-success` in the above function.

**Comment by kanghj** [comment]
Perhaps we should store status message colour in AjaxResult.

**Comment by taniach** [comment]
It already takes in a list of StatusMessage objects in the constructor which store the colour.

**Comment by taniach** [comment]
Why did we include a JS method that overwrites the status message colour?

**Comment by kanghj** [comment]
Oh, I meant send the status message colour as part of the json response. 

Because the issue for submitting the edit form was done at the same time as the status message colour issue, so @bamboo3250 probably wasn't aware that the status message colour for the edit form was changed.

**Comment by taniach** [comment]
`bindFeedbackSessionEditFormSubmission()` in `instructorFeedbackEdit.js` assigns `danger` for error and `warning` for success. Should change it to `success`.
