### ISSUE TITLE
Submission counter algorithm is flawed

### ISSUE THREAD

**Issue by junhaoyap** [TEAMMATES/repo#4271]
<img width="1258" alt="screen shot 2015-09-12 at 7 49 40 pm" src="https://cloud.githubusercontent.com/assets/6291947/9835193/bd01fc76-5992-11e5-9961-ba491861a5d1.png">

Anyone knows something about this?

**Comment by junhaoyap** [comment]
I'm thinking this might be a location based error rather than a Mac specific error, I dial-ed the date by 1 day for all the dates in the test and it seems to pass, @kanghj no one else is failing this right? If no one else failing I might as well just close this and I can fail it alone :p

**Comment by damithc** [comment]
I suspect it is location based too. Even then, we should fix it (because it will affect contributors from overseas) and now we have a good opportunity to fix it because you can reproduce it. So go for it.

**Comment by junhaoyap** [comment]
Good call, ok I will work on it when I can get a larger chunk of time, I might need a larger chunk of time to read up to be able to solve this!

**Comment by wkurniawan07** [comment]
Very soon I'll be facing this too I think :p

**Comment by damithc** [comment]
@wkurniawan07 was this a problem for you while you were overseas?

**Comment by wkurniawan07** [comment]
Strangely, no. Perhaps because I lived on the GMT line :p
Anyway, I just took a quick check on this issue, and made an alarming discovery: the submission counter algorithm is flawed all along. In fact, the numbers shown on the picture above are the correct ones for the first 2 cases, and for the third case neither is correct.
@junhaoyap I'll be taking over this issue, will finish it in no time. Your worries will soon be no more :ok_hand:
