### ISSUE TITLE
Regex for regkey in God mode too lenient and potentially dangerous

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4366]
Similar to #4361.
In particular, the third one: `"([a-zA-Z0-9-_]){50,}"`, the ones where `Const.ParamsNames.REGKEY` is involved are okay. It means that _all_ combinations of alphabets, numbers, -, and _ of length 50 and more, wrapped around double quotes, will be replaced.
It does replace the regkey wrapped in double quotes, but there are so many more stuffs that are replaced by this. This time there are more unwanted changes.

**Comment by damithc** [comment]
What else in our test html files has >50 numbers and letters wrapped by double quotes?

**Comment by damithc** [comment]
Keep in mind that God mode is for testing only. As long as the test data is unlikely to have certain problematic data, we don't have to handle it. Sure, it is nice if the god mode can handle any kind of weird data if it can be done without much extra effort, but it is not critical to do so, especially if it is easy to detect when the current god mode breaks due to a weird test data.
