### ISSUE TITLE
Admin UI tests in full run failing due to admin username contamination

### ISSUE THREAD

**Issue by wkurniawan07** [TEAMMATES/repo#4377]
The actual cause has not been remedied up to now. Removing HTML comparisons imho is an overkill solution (although it works and I won't say no to it, hey no HTML comparison means it's faster). Here's the actual cause: _almost every single_ UI test has admin login in it. As the result, the admin UI tests are badly contaminated. So the true solution is to allow an alternative login with _no_ admin privilege, and reserve the admin privilege only to admin UI tests. It should make sense -- there's supposedly only one admin for the app!

P.S. If we still go into the path of removing all HTML comparisons, at least fixing this will make life easier until all the comparisons are gone :p

**Comment by damithc** [comment]
I thought the cause of failure is extra data?. The admin can see all data, so as long as the database has non-test data, some of the admin UI tests will have unpredictable data in them.
The reason we use an admin login for instructor tests is because admin can masquerade as any user, avoiding the need to login/out hundreds of times during tests.

**Comment by damithc** [comment]
To clarify, using the admin login for instructor tests is not the cause of contamination. Admin sees all data no matter which login was used to create those data. The contamination is inherent and unavoidable, unless we wipe out the database before admin tests, which is of course a clear NO NO.

**Comment by wkurniawan07** [comment]
The extra data are all wildcarded. The session contamination causes the `${test.admin}` name to be replaced by whichever session going on concurrently at that time and that fails the HTML comparison.

I've successfully got rid of the problem in dev using the solution I lined out. Will try staging very soon.

**Comment by wkurniawan07** [comment]
I found a simpler, cleaner solution: always logout first and re-login in admin UI tests. That will ensure that the session is under the correct admin username. Works in dev, here's proof; used to be 10+ errors in the first run before as all admin tests will fail:
![image](https://cloud.githubusercontent.com/assets/7261051/10123618/98334af0-6570-11e5-82bd-912a596a3033.png)
Will try in staging tomorrow, my quota for today is already busted :p

**Comment by kanghj** [comment]
Just to comment on the part about wildcard-ing away the extra data. IIRC, one problem was that the wildcards in the admin html tests didn't really fit the workflow since godmode wouldn't be able to correctly regenerate the wildcards in those pages, and that most of the page was wildcarded anyway. It's probably not worth the cost and time to perform a full page check, and then wildcard pretty much all content on that page anyway?

**Comment by wkurniawan07** [comment]
Yes, I agree with that. I'm sure godmode can be powered up even more to also handle admin test data (in my head I've thought of at least one way), but it all goes to whether it's worth it or not. If there are no interesting things that need explicit HTML checking, then it's true that HTML comparison is not worth it.

Fixing this can be a permanent solution, or just a temporary solution for those who are fed up enough to see their tests failing (like me :p). I'm all for whichever's the best.
