### ISSUE TITLE
admin activity log: Give a way to search more logs when searching for activities of a user

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4511]
Currently, there is no option to 'search more'
![image](https://cloud.githubusercontent.com/assets/1673303/10657237/bef052f2-78ba-11e5-9e83-21fa3dc30a46.png)

**Comment by damithc** [comment]
@bamboo3250 see if you can do this too.

**Comment by bamboo3250** [comment]
In this case, the number of logs didn't reach MAX_LOGSEARCH_LIMIT, which means those were all logs that the LogService could find. Therefore, the "Search More" button didn't appear. It will appear only when the total logs gone through in last search reaches 15000.

**Comment by damithc** [comment]
That's odd because we have several days worth of logs and certainly more than 15,000 entries. Even if there are no more logs in this version of the app, the search is supposed to go through logs from previous versions of the app. Here's another example:
![image](https://cloud.githubusercontent.com/assets/1673303/10748790/9801a820-7c9e-11e5-85ab-909fa8d0ce61.png)
I can confirm we have logs on 24th Oct (from the same app version)
![image](https://cloud.githubusercontent.com/assets/1673303/10748817/cfd980ce-7c9e-11e5-9117-655d8183ea54.png)
We also have logs on 23rd Oct (from previous version of the app)
![image](https://cloud.githubusercontent.com/assets/1673303/10748877/625a8b78-7c9f-11e5-98c8-42db4309e933.png)

**Comment by damithc** [comment]
Here's another one, performed today 11.40am. Looks like the search goes back only as far as the last 24 hours.
![image](https://cloud.githubusercontent.com/assets/1673303/10748938/f22de98e-7c9f-11e5-899e-b11dac13b23c.png)

**Comment by bamboo3250** [comment]
Ah, the default log search range is limited to one day only since #4370. It's possible to change this range when clicking Search More option.

**Comment by damithc** [comment]
The limit is fine. I just need a link 'search more' to appear at the bottom so that I can extend the search to one more day at a time.

**Comment by bamboo3250** [comment]
It seems that the function to extend the search to one more day hasn't been implemented yet. Could you confirm this? @thyageshm

**Comment by damithc** [comment]
I'm looking for this link. ![image](https://cloud.githubusercontent.com/assets/1673303/10750235/063bda0e-7cae-11e5-9664-904a60db3be1.png)
We had something like that previously, which even had the ability to auto-load in a loop until we found enough entries. However, it started costing us money when the loop went on for too long. That's why we introduced a 24 hour limit. It was meant to be a limit on auto-loading, not a limit on manual search. Looks like we lost the ability to extend the search to older logs when introducing the 24 hour limit.

**Comment by thyageshm** [comment]
It is true. Since I included the time restriction in the query that is sent to GAE, if the number of log entries in one day does not exceed 50, it does not show the "older logs" link. 
This problem should not occur if the time is specified in the query by the admin.

I overlooked this bit that the logic used to show the "older logs link" depends on the query sent to GAE. A solution is this:
1. Add a boolean flag in AdminActivityLogPageData to keep track of whether a start date has been specified (variable that holds this value is called ```fromDateValue``` and the boolean flag is to be set in ```line 294``` inside the ```else if```` block that checks if the "from" label has been given in the query

2. In AdminActivityLogPageAction update the ```if``` condition on ```line 231```:
from
```if (currentLogsInPage >= LOGS_PER_PAGE) {```
to
```if (currentLogsInPage >= LOGS_PER_PAGE || data.hasDefaultStartDate()) {```

This should handle the problem.

**Comment by bamboo3250** [comment]
I think this problem can be solved by checking whether the query is empty or not. If it is empty, the default 24-hour limit will be applied. Otherwise, (if it is manual search), it will be like it was before, the limit will only be applied if it is clearly stated in the query.

**Comment by thyageshm** [comment]
I don't get what you are saying

**Comment by bamboo3250** [comment]
The problem is the log search cannot go further because of 24-hour limit when searching period is not defined in the query. So it can be solved by checking the query:
1. if the query is empty, 24-hour limit will be applied
2. if the query is not empty, the searching period will be applied only when the admin want to do so.

**Comment by wkurniawan07** [comment]
I'm not sure if what I'm going to say has anything to do with the issue at hand, but the fact that the current version is 5.58.02 (has a patch version) means that the log query can't go to any other version than that (see #4417, #4454).

**Comment by damithc** [comment]
This needs fixing soon. My ability to support user queries is severely hampered by this.

**Comment by thyageshm** [comment]
@bamboo3250 I guess you can implement your solution first, then if there is anything we can point it out in the diffs
