### ISSUE TITLE
Duplicate students in MCQ 

### ISSUE THREAD

**Issue by damithc** [TEAMMATES/repo#4576]
Database seems to be clean (no duplicate students in the database).
![image](https://cloud.githubusercontent.com/assets/1673303/11315829/feb95e98-9033-11e5-8105-75e0c33077cd.png)
Funny thing is there are no duplicates in other similar questions in the same session.
![image](https://cloud.githubusercontent.com/assets/1673303/11315819/d45a3ca8-9033-11e5-813c-3ce18e754947.png)
The one with duplicates is the last question of the session

**Comment by damithc** [comment]
When I preview the session as the same student, there are no duplicates. 
Only some students in that course seem to have this problem.

**Comment by damithc** [comment]
Is it possible for responses from another session to cause the duplicates? The exact same question appears in another session of the same course.

**Comment by kanghj** [comment]
It should not be possible for responses in another session to affect the session. For the affected students, are there responses from the students to the duplicated recipients?

**Comment by damithc** [comment]
There are no duplicate responses, even when I ignore course ID and session name (search for matching giver, receiver, and question ID), I can't find duplicate responses. 
Here's another funny thing. The answers for this MCQ question is 'Yes' and 'No'. No matter what the answer is for the first set, the second set is always 'No'. So this seems to be an error in how the form is rendered.

**Comment by damithc** [comment]
In this particular question, there seems to be a mix up of team and name. In the results, team number shows up under the name and the team is blank. There is no such problem in other questions.
![image](https://cloud.githubusercontent.com/assets/1673303/11321617/062eaba0-9102-11e5-8845-c3452e9c7225.png)

**Comment by damithc** [comment]
OK, I think I figured out the cause of the problem. The question has a weird feedback path.
![image](https://cloud.githubusercontent.com/assets/1673303/11321635/a5889a94-9102-11e5-91d9-ace98fd5b43c.png). It was most likely a mistake by the instructor.

**Comment by damithc** [comment]
Nevertheless, it is still a legitimate feedback path and I don't think it is being handled correctly by us.

**Comment by kanghj** [comment]
I don't think the cause of the problem is specifically the feedback path, otherwise this should happen for every student? 

Usually for questions with team givers, there should only be a single response from the team. This constraint is however, not enforced at any point in our code. What is likely happening is that two students in the team opened up the submission page at roughly the same time, before there are responses from the team. So now both responses from the two students will be accepted and there are now two responses from the same team. 

We might not have a way now to resolve the existing duplicates programmatically, other than maybe looking through the logs and seeing who submitted more recently? A way to prevent further occurrences of this is to lookup the datastore for responses from the team during submission, but this will be susceptible to eventual consistency. Another possible fix is #4486, but we won't be able to alert students of conflicts during submission.

**Comment by thyageshm** [comment]
If there is a way to aggregate the answers from the members in the team before showing the response, I think we can circumvent the problem cleanly. For example, if the question has a text response, an aggregate function would be to concatenate the responses with a couple of endlines to separate them

**Comment by kanghj** [comment]
That would involve changing the way team responses currently work (from a single response a team, to allowing each team member to have a response)?

What I meant by 'not enforced in our code' is that we assume that each team member submits responses at a different time. After the first student has created the response, the second student in the team will see the response written by the first student and can modify/delete it, but not write a new response. 

However, in this case when they go to the submission page at the same time, they both don't see an existing response, and so both submissions will end up creating a new response.

**Comment by damithc** [comment]
I think overwriting the older response with the new response is the way to go. I thought that's how it is supposed to work already. Yes, the giver should be team name.
Enhancements that can be done as separate issues:
1. Perhaps we should let the respondent know that it is a team question and they are entering on behalf of the entire team.
2. Track the edit history of responses, so that we know who edited the response and when. This feature is useful for most entities, not just responses.
@kanghj can you create issues for the above?
